services:

  db:
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: TechnicalTest
    volumes:
      - ./postgres:/var/lib/postgresql/data

  backend:
    build: ./server
    container_name: nest_api
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db

  frontend:
    build: ./client
    container_name: react_app
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend